name: CI

on:
  workflow_run:
    workflows:
      - 'pipeline'
    types: [requested, in_progress, completed]

# Minimum required permissions for the integration workflow
permissions:
  actions: read
  contents: read
  pull-requests: read

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  octane_integration:
    runs-on: ubuntu-latest
    name: OctaneIntegration#${{github.event.action}}#${{github.run_id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: opentext/sdp-github-actions-integration@v26.2.1
        with:
          octaneUrl: 'https://almoctane-eur.saas.microfocus.com'
          octaneSharedSpace: 411029
          octaneWorkspace: 12001
          octaneClientId: ${{ secrets.SDP_CLIENT_ID }}
          octaneClientSecret: ${{ secrets.SDP_CLIENT_SECRET }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          serverBaseUrl: https://github.com/davbaster/junit-calculator-gha2
          logLevel: '2'
          pipelineNamePattern: '${workflow_name}'
          unitTestResultsGlobPattern: "**/*.xml"
          testingFramework: 'junit'
