name: CI

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run JUnit tests
        run: mvn test
      - name: Log workflow execution parameters
        run: |
            echo "execution_parameter:: $(echo '${{ toJson(github.event.inputs) }}' | jq -c .)"

  octane_integration:
    needs: test
    runs-on: ubuntu-latest
    name: OctaneIntegration#${{github.event.action}}#${{github.run_id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@0c811efb268e4da46b191083de58644e6bfb4353
        with:
          octaneUrl: 'https://almoctane-eur.saas.microfocus.com'
          octaneSharedSpace: 411029
          octaneWorkspace: 12001
          octaneClientId: ${{ secrets.OCTANE_CLIENT_ID }}
          octaneClientSecret: ${{ secrets.OCTANE_CLIENT_SECRET }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          serverBaseUrl: https://github.com/davbaster/junit-calculator-gha2
          pipelineNamePattern: '${workflow_name}'
          unitTestResultsGlobPattern: '**/target/surefire-reports/*.xml'
          testingFramework: 'junit'
